version: '3.7'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - localprom
    ports:
      - 9090:9090
  node-exporter:
    image: prom/node-exporter
    networks:
      - localprom
    ports:
      - 9100:9100
  pushgateway:
    image: prom/pushgateway
    networks:
      - localprom
    ports:
      - 9091:9091
networks:
  localprom:
    driver: bridge
