"""GPU device module for Zeus. Abstraction of GPU devices."""
from zeus.device.gpu import (
    get_gpus,
    ZeusInitGPUError,
    ZeusInvalidArgGPUError,
    ZeusNotSupportedGPUError,
    ZeusNoPermissionGPUError,
    ZeusAlreadyInitializedGPUError,
    ZeusNotFoundGPUError,
    ZeusInsufficientSizeGPUError,
    ZeusInsufficientPowerGPUError,
    ZeusDriverErrorGPUError,
    ZeusTimeoutGPUError,
    ZeusIRQErrorGPUError,
    ZeusLibraryNotFoundGPUError,
    ZeusFunctionNotFoundGPUError,
    ZeusCorruptedInfoROMGPUError,
    ZeusLostGPUGPUError,
    ZeusResetRequiredGPUError,
    ZeusOperatingSystemGPUError,
    ZeusLibRMVersionMismatchGPUError,
    ZeusMemoryGPUError,
    ZeusUnknownGPUError,
)