"""GPU device module for Zeus. Abstraction of GPU devices."""
from zeus.device.gpu import (
    get_gpus,
    ZeusGPUInitError,
    ZeusGPUInvalidArgError,
    ZeusGPUNotSupportedError,
    ZeusGPUNoPermissionError,
    ZeusGPUAlreadyInitializedError,
    ZeusGPUNotFoundError,
    ZeusGPUInsufficientSizeError,
    ZeusGPUInsufficientPowerError,
    ZeusGPUDriverError,
    ZeusGPUTimeoutError,
    ZeusGPUIRQError,
    ZeusGPULibraryNotFoundError,
    ZeusGPUFunctionNotFoundError,
    ZeusGPUCorruptedInfoROMError,
    ZeusGPULostError,
    ZeusGPUResetRequiredError,
    ZeusGPUOperatingSystemError,
    ZeusGPULibRMVersionMismatchError,
    ZeusGPUMemoryError,
    ZeusGPUUnknownError,
)