name: Check format, lint, and test

on:
  push:
    paths:
      - '.github/workflows/fmt_lint_test.yaml'
      - 'zeus/**'
      - 'tests/**'
      - 'capriccio/*.py'
      - 'examples/**'
      - 'setup.py'
      - 'scripts/lint.sh'
      - 'pyproject.toml'

# Jobs initiated by previous pushes get cancelled by a new push.
concurrency:
  group: ${{ github.ref }}-lint-and-test
  cancel-in-progress: true

jobs:
  format_lint_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip'
      - name: Install Zeus and lint tools
        run: pip install -U pip && pip install ".[dev]"
      - name: Check format and lint
        run: bash scripts/lint.sh
      - name: Run tests
        run: python -m pytest
