name: Publish Python package to PyPI

on:
  push:
    tags:
      - zeus-v*

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ml-energy'
    permissions:
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
          cache: 'pip'
      - name: Build source distribution
        run: pip install build && python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
