name: (Zeusd) Check format, lint, and test
permissions:
  contents: read

on:
  pull_request:
    paths:
      - '.github/workflows/zeusd_fmt_lint_test.yaml'
      - 'zeusd/**'
  push:
    paths:
      - '.github/workflows/zeusd_fmt_lint_test.yaml'
      - 'zeusd/**'

# Jobs initiated by previous pushes get cancelled by a new push.
concurrency:
  group: ${{ github.ref }}-zeusd-lint-and-test
  cancel-in-progress: true

jobs:
  fmt:
    if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository }}
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: zeusd
      - name: Install the Rust toolchain
        run: rustup toolchain install stable --profile minimal --component rustfmt
      - name: Check format
        run: cargo fmt --all --check
        working-directory: zeusd

  clippy_and_test:
    if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository }}
    name: clippy + test (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: zeusd
      - name: Install the Rust toolchain
        run: rustup toolchain install stable --profile minimal --component clippy
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            zeusd/target/
          key: ${{ github.event.repository.name }}-${{ runner.os }}-zeusd-cargo-v3
      - name: Run clippy
        run: cargo clippy --all-targets -- -D warnings
        working-directory: zeusd
      - name: Run tests
        run: cargo test
        working-directory: zeusd
